# Generated by Django 4.2.2 on 2023-07-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingsettings',
            old_name='end_mailing',
            new_name='end_mailing_time',
        ),
    ]
