# Generated by Django 4.2.2 on 2023-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='last_try_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки'),
        ),
    ]
