# Generated by Django 4.2.2 on 2023-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0002_alter_mailingsettings_mailing_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_periodicity_display',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_periodicity',
            field=models.CharField(choices=[('M H * * *', 'Раз в день'), ('M H * * 1', 'Раз в неделю'), ('M H 1 * *', 'Раз в месяц')], max_length=40, verbose_name='периодичность в формате crontab'),
        ),
    ]
