# Generated by Django 4.2.2 on 2023-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0002_alter_mailinglogs_last_try_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='server_response',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ сервера'),
        ),
    ]
