# Generated by Django 4.2.2 on 2023-07-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
