# Generated by Django 4.2.2 on 2023-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0003_mailingsettings_mailing_periodicity_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('создана', 'Создана'), ('отправляется', 'Отправляется'), ('завершена', 'Завершена')], default='создана', max_length=20, verbose_name='cтатус'),
        ),
    ]
