# Generated by Django 4.2.2 on 2023-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0003_alter_mailinglogs_server_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='try_status',
            field=models.CharField(max_length=250, verbose_name='статус попытки'),
        ),
    ]
