# Generated by Django 4.2.2 on 2023-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_management', '0003_mailingsettings_mailing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_is_active',
            field=models.BooleanField(default=True, verbose_name='Рассылка активна'),
        ),
    ]
