# Generated by Django 4.2.2 on 2023-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('text', models.TextField(verbose_name='Текст поста')),
                ('image', models.ImageField(upload_to='post_img', verbose_name='Изображение поста')),
                ('views_count', models.PositiveIntegerField(verbose_name='Количество просмотров')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-published_at'],
            },
        ),
    ]
