# Generated by Django 4.2.2 on 2023-07-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='почта')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='фамилия')),
                ('surname', models.CharField(blank=True, max_length=250, null=True, verbose_name='отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('first_name', 'last_name', 'surname'),
            },
        ),
    ]
