# Generated by Django 4.2.2 on 2023-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='почта')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.CharField(max_length=100, verbose_name='время')),
                ('mailing_periodicity', models.CharField(max_length=10, verbose_name='периодичность')),
                ('mailing_status', models.CharField(max_length=10, verbose_name='cтатус')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылок',
                'ordering': ('mailing_status',),
            },
        ),
        migrations.CreateModel(
            name='MailingMassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_subject', models.CharField(max_length=250, verbose_name='тема сообщения')),
                ('massage_text', models.TextField(verbose_name='текст сообщения')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.mailingsettings', verbose_name='id настроек')),
            ],
            options={
                'verbose_name': 'тема сообщения',
                'verbose_name_plural': 'темы сообщений',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now=True, verbose_name='дата и время попытки')),
                ('try_status', models.CharField(max_length=10, verbose_name='статус попытки')),
                ('server_response', models.CharField(max_length=250, verbose_name='ответ сервера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mail_sender.client', verbose_name='id клиента')),
                ('mailing_massage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mail_sender.mailingmassage', verbose_name='id сообщения')),
            ],
            options={
                'verbose_name': 'Логи',
                'ordering': ('last_try_date',),
            },
        ),
    ]
