# Generated by Django 4.2.2 on 2023-06-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingMassage',
            new_name='MassageToSend',
        ),
        migrations.AlterModelOptions(
            name='massagetosend',
            options={'verbose_name': 'Сообщение для рассылки', 'verbose_name_plural': 'Сообщения для рассылки'},
        ),
        migrations.RenameField(
            model_name='mailinglogs',
            old_name='mailing_massage',
            new_name='massage_to_send',
        ),
    ]
