# Generated by Django 4.2.2 on 2023-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(default='Создана', max_length=10, verbose_name='cтатус'),
        ),
    ]
