# Generated by Django 4.2.2 on 2023-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_periodicity',
            field=models.CharField(choices=[('M H */1 * *', 'раз в день'), ('M H * * 1', 'раз в неделю'), ('M H * */1 *', 'раз в месяц')], max_length=40, verbose_name='периодичность'),
        ),
    ]
