# Generated by Django 4.2.2 on 2023-06-28 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_rename_mailingmassage_massagetosend_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglogs',
            options={'ordering': ('last_try_date',), 'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
    ]
