# Generated by Django 4.2.2 on 2023-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_alter_mailingsettings_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_periodicity',
            field=models.CharField(choices=[('M H */1 * *', 'Раз в день'), ('M H * * 1', 'Раз в неделю'), ('M H * */1 *', 'Раз в месяц')], max_length=40, verbose_name='периодичность'),
        ),
    ]
