# Generated by Django 4.2.2 on 2023-06-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0002_alter_mailingsettings_mailing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsettings',
            name='mailing_time',
        ),
    ]
