# Generated by Django 4.2.2 on 2023-07-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_remove_mailingsettings_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_periodicity',
            field=models.CharField(max_length=20, verbose_name='периодичность'),
        ),
    ]
