# Generated by Django 4.2.2 on 2023-07-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0003_alter_mailingsettings_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mail_sender.mailing', verbose_name='рассылка'),
        ),
    ]
