# Generated by Django 4.2.2 on 2023-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_alter_mailingsettings_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('отправляется', 'Отправляется'), ('отправлена', 'Отправлена')], default='Создана', max_length=20, verbose_name='cтатус'),
        ),
    ]
