# Generated by Django 4.2.2 on 2023-07-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0004_alter_mailingsettings_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_periodicity',
            field=models.CharField(max_length=40, verbose_name='периодичность'),
        ),
    ]
