# Generated by Django 4.2.2 on 2023-07-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0005_alter_mailingsettings_mailing_periodicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglogs',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailinglogs',
            name='massage_to_send',
        ),
    ]
