# Generated by Django 4.2.2 on 2023-07-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0005_alter_mailingsettings_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_status',
            field=models.CharField(choices=[('создана', 'Создана'), ('отправляется', 'Отправляется'), ('отправлена', 'Отправлена')], default='создана', max_length=20, verbose_name='cтатус'),
        ),
    ]
