# Generated by Django 4.2.2 on 2023-07-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0006_remove_mailinglogs_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
