# Generated by Django 4.2.2 on 2023-07-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0007_mailingsettings_mailing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massagetosend',
            name='mailing_settings',
        ),
    ]
