# Generated by Django 4.2.2 on 2023-07-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0008_remove_massagetosend_mailing_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassageToSend',
            new_name='Mailing',
        ),
    ]
