# Generated by Django 4.2.2 on 2023-07-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail_sender', '0009_rename_massagetosend_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglogs',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_sender.mailing', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='mailingsettings',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_sender.mailing', verbose_name='рассылка'),
        ),
    ]
